spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3305/${MYSQL_DATABASE}"
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show-sql: true
        format_sql: true
#        generate_statistics: true # required for Hibernate to start collecting statistics
    open-in-view: false # when false, it avoids performance problems and forces the use of the Transactional annotation
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
logging:
  level:
    ROOT: INFO
    org:
      hibernate:
        SQL: DEBUG
#        stat: DEBUG
        LazyInitializationException: DEBUG
      springframework: INFO
    web: ERROR
    liquibase: ERROR