application:
  url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}
  username: ${MYSQL_USER}
  password: ${MYSQL_PASSWORD}
#server:
#  port: 8484
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${application.url}
    username: ${application.username}
    password: ${application.password}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        # required for Hibernate to start collecting statistics
        generate_statistics: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
logging:
  level:
    ROOT: INFO
    org:
      hibernate:
        SQL: DEBUG
      springframework: INFO
    web: ERROR
    liquibase: ERROR